### PR TITLE
Update Open-WinSCPSession.ps1 to add FileTransferProgress event handling

### PR DESCRIPTION
**Pull request by owainhunt**
Add a ScriptBlock parameter. This script block is executed roughly every second while any file transfer operation is under way, in response to the FileTransferProgress event.

### CODE REVIEW

**Comment by dotps1** [comment]
Can you give me an example of this usage? 

Also, with the next release, the session object will be one cmdlet, ```New-WinSCPSession``` there will no longer be ```New-WinSCPSessionOptions``` or ```Open/Close-WinSCPSession```  Please see the Alpha Branch.

**Comment by owainhunt** [comment]
From http://winscp.net/eng/docs/library_session_filetransferprogress#example
 ```powershell
function FileTransferProgress
{
    param($e)
 
    # New line for every new file
    if (($script:lastFileName -ne $Null) -and
        ($script:lastFileName -ne $e.FileName))
    {
        Write-Host
    }
 
    # Print transfer progress
    Write-Host -NoNewline ("`r{0} ({1:P0})" -f $e.FileName, $e.FileProgress)
 
    # Remember a name of the last file reported
    $script:lastFileName = $e.FileName
}

Open-WinSCPSession ... -ScriptBlock { FileTransferProgress($_) }
  ```

Logs "file name (x%)" every second or so, and because of the carriage return at the start of the comment, does it in place rather than writing a new line for each update. 

The FileTransferProgress event handler needs to be set before the session is opened, so in the alpha branch this could slot into New-WinSCPSession.ps1 in the try block around line#207.

**Comment by dotps1** [comment]
that's pretty nice, it may be nice just to be a default behavior.  I will more and merge something into the Alpha Branch.  Thanks!

**Comment by dotps1** [comment]
I added the ScriptBlock Parameter to the New-WinSCPSession Cmdlet, however, i did not really like functionality of the example function.  You can pass the scriptblock for now.  I will right a better helper function.  I tried to replace the Write-Host with Write-Output, it didn't seem to like that.

Thanks.

**Pull request closed without merging**
